Feature/cod 149 refactor payload token
coders-app/coders-app-identity-server pull request #103
Opened 2023-04-19 15:05 UTC by Jbar91

2023-04-19 16:06 UTC, AnnaMaPe commented
@MMLORENA y @Jbar91 el tipado de CustomTokenPayload usado para verifyToken extiende del tipado de JwtPayload, este último no aceptaría tipar el error como JsonWebTokenError?

2023-04-19 16:23 UTC, mariogl commented on src/server/types.ts
> +export interface CustomTokenPayload extends JwtPayload {
Hay que separar estas interfaces con líneas en blanco.

2023-04-19 16:33 UTC, mariogl commented
> @coders-app/devs Tenemos dudas con el comportamiento de `jwt.verify`. Realmente la función devuelve un string o un jwtPayload decodificado. Por eso hemos hecho que el if comprueve que tenga una propiedad id y sino entonces throwee. Quizás no sea la mejor opción, pero no encontramos otra.
> 
> Revisando la docu entendemos, quizás erroneamente que la función puede throwear cuando se usa el tercer parámetro que acepta de callback pero no podemos configurarlo por el tipado del `verifyToken` dado que le decimos que es un CustomPayload y entonces no nos acepta tipar el error dentro de la callback como `JsonWebTokenError`.
> 
> ```js
> jwt.verify(token, 'shhhhh', function(err, decoded) {
>   if (err) {
>     /*
>       err = {
>         name: 'JsonWebTokenError',
>         message: 'jwt malformed'
>       }
>     */
>   }
> });
> ```

`jwt.verify()` throwea cuando la verificación del token falla, y el error que throwea tiene las propiedades `name` y `message`. Por tanto el código que teníamos antes no estaba bien, y no lo hemos sabido porque no testeábamos el caso real en el que el método throweaba. En el test hacíamos que retornara en vez de throwear:

`jwt.verify = jest.fn().mockReturnValueOnce(jwtError);`

2023-04-19 16:37 UTC, mariogl requested changes

2023-04-19 16:37 UTC, mariogl commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
Este caso de error lo tenemos que gestionar en el catch, porque `jwt.verify´ throweará.

2023-04-19 16:52 UTC, MMLORENA commented
> @MMLORENA y @Jbar91 el tipado de CustomTokenPayload usado para verifyToken extiende del tipado de JwtPayload, este último no aceptaría tipar el error como JsonWebTokenError?

No, no lo aplica porque toma solo como CustomPayload y no incluye el tipado de JsonWebTokenError sería aparte

2023-04-19 18:58 UTC, mariogl commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
¿Habéis probado esto? https://stackoverflow.com/a/50656680/574218

2023-04-19 19:30 UTC, MMLORENA commented on src/server/types.ts
> +export interface CustomTokenPayload extends JwtPayload {
hecho

2023-04-19 19:31 UTC, MMLORENA commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
No, no lo había probado pero ha funcionado, no había pensado de hacerlo de esta forma. Muchas gracias!! Anotado para las próximas

2023-04-19 19:33 UTC, MMLORENA commented
> * Refactor CustomTokenPayload y mockTokenPayload eliminando sus propiedades name e isAdmin
> * Modificar verifyToken guard cuando no tiene un id valido, esto sucede por el tipado que tiene puesto el CustomTokenPayload que no contiene los tipados del `JsonWebTokenError` el cual tiene como propiedades name y message que son las que se deberian de comprobar para el throw del error

- Se ha eliminado la comprobación de si `verifyToken` no devuelve un objeto con propiedad `id` puesto que la función `jwt.verify` throwea y el test se ha cambiado el mock de la función a un `jest.fn( ).mockImplementation( ( ) => { throw new Error ( ) }`.

2023-04-19 19:40 UTC, Jbar91 commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
Y en este caso se utiliza el `mockImplementation` porque se testea que el mismo método `jwt.verify` internamente ya hace el throw?

2023-04-19 20:22 UTC, mariogl commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
No, aquí lo que estáis haciendo es mockear `jwt.verify` para anular su implementación real y poner vosotros la vuestra. En este caso la implementación "falsa" es que simplemente throwee, y así imitáis el comportamiento de `jwt.verify` cuando la verificación del token falla.

En el fondo lo que estás haciendo es "oye, middleware auth, voy a comprobar que cuando `jwt.verify` te throwea tú te comportas como te tienes que comportar"

2023-04-19 20:23 UTC, mariogl approved these changes

2023-04-19 21:44 UTC, MMLORENA commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
En este caso mockeamos el jwt.verify pq es una librería y suponemos q sus creadores ya han testeado qué hace lo que debe hacer. Por eso imitamos su comportamiento anulandolo con un mock. Lo que nos pasaba es que estabamos intentando devolver el error con `mockReturnValue` pero en verdad queríamos que throweara. Los matchers de reject si no me equivoco son para hacer rejectear promesas y está función era syncrona por eso tampoco nos servían.

2023-04-20 07:33 UTC, Jbar91 commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
Ok, entendido

2023-04-20 10:20 UTC, MMLORENA commented on src/server/middlewares/auth/auth.ts
> +    if (!verifyToken.id) {
@mariogl resuelvo yo la conversación para poder mergear

2023-04-20 10:23 UTC, merged