Feature/cod 154 mocked tokens generating function
coders-app/coders-app-identity-server pull request #105
Opened 2023-04-21 15:07 UTC by DI3BOSS

[ ✓ ]  Creada la función `generateMockToken` en `mockToken.ts` para generar "_mockens_" para testing.
[ ✓ ]  Cambiados los `imports` y las instancias en los tests que usaban la variable `mockenToken`.
[ ✓ ]  Recogido el valor al que resuelve `generateMockToken()` en una variable en `userControllers.test.ts` para prevenir un `undefined` que devolvía en uno de los casos de uso y que rompía el test.

2023-04-21 16:20 UTC, MMLORENA commented on src/testUtils/mocks/mockToken.ts
>    id: new mongoose.Types.ObjectId().toString(),
La función de generateMockToken siempre se va a generar con el mismo id y está tarea surgió de la necesidad de tener un mockTokenPayload diferente para distintos caso de uso. Por ello, la función generateMockToken debería recibir por parámetros una id para tener un mockTokenPayload customizado para cada test.

2023-04-21 16:21 UTC, MMLORENA requested changes
Y no he entendido en qué caso devuelve el mockToken undefined y qué has hecho para arreglarlo. ¿puedes indicar archivo?

2023-04-21 19:55 UTC, DI3BOSS commented on src/testUtils/mocks/mockToken.ts
>    id: new mongoose.Types.ObjectId().toString(),
Vale resuelta mi duda de la "inutilidad" de implementar una función que devuelva un mocken generado siempre igual 😅 .

Entonces refactorizo para pasar por parámetros el id del user.  Pregunta:

> ¿Como argumento tomaremos el id que se use en cada test que necesite de un mocken?

2023-04-21 20:11 UTC, DI3BOSS commented
> Y no he entendido en qué caso devuelve el mockToken undefined y qué has hecho para arreglarlo. ¿puedes indicar archivo?

Cierto, no me he explicado bien 😅.

Al refactorizar los test que necesitarían de `generateMockToken` veía que se me rompía un test. Al _debuggear_, lanzando la suite de test `userControllerTest` (línea 157). En los demás tests, la función `generateMockToken`, al ser llamada, me devolvía un `mockToken`, pero en este caso de uso, este `expect`:

`expect(res.cookie).toHaveBeenCalledWith(cookieName, generateMockToken(), {
        httpOnly: true,
        maxAge: cookieMaxAge,
        sameSite: "none",
        secure: true,
      });
`
me devolvía undefined. 

Por ello, se me ocurrió invocar la función antes del `expect` y almacenar el valor que devolvía dentro de una variable para luego   usarla en dicho `expect` y prevenir el undefined. 

Ahora bien, no he conseguido ver porque la función aquí resuelve a `undefined`, como no sea por el _matcher_ que usamos en el _assert_ del test...

2023-04-21 20:27 UTC, mariogl commented
@DI3BOSS no hacemos un commit por un cambio de nombre de variable o por cambios en los imports. Cuando hagas los cambios, acuérdate de comprimir commits para que en cada commit haya cambios relevantes.

2023-04-21 20:45 UTC, MMLORENA commented on src/testUtils/mocks/mockToken.ts
>    id: new mongoose.Types.ObjectId().toString(),
@DI3BOSS no entiendo la pregunta. La función `getMockToken` tiene que recibir una `id` como parámetro para darle a la variable de `mockUserPayload` el valor que reciba la función y así en cada test cuando invoquemos se podra generar un token diferente porque le cambiará el payload.

¿Aclara esto tu duda?

2023-04-21 20:52 UTC, MMLORENA commented
> > Y no he entendido en qué caso devuelve el mockToken undefined y qué has hecho para arreglarlo. ¿puedes indicar archivo?
> 
> Cierto, no me he explicado bien 😅.
> 
> Al refactorizar los test que necesitarían de `generateMockToken`, veía que se me rompía un test. Al _debuggear_, lanzando la suite de test `userControllerTest` (línea 157). En los demás tests, la función `generateMockToken`, al ser llamada, me devolvía un `mockToken`, pero en este caso de uso, este `expect`:
> 
> `expect(res.cookie).toHaveBeenCalledWith(cookieName, generateMockToken(), { httpOnly: true, maxAge: cookieMaxAge, sameSite: "none", secure: true, }); `
> 
> me devolvía `undefined`.
> 
> Por ello, se me ocurrió invocar la función antes del `expect` y almacenar el valor que devolvía dentro de una variable para luego usarla en dicho `expect` y prevenir el undefined.
> 
> Ahora bien, no he conseguido ver porque la función aquí resuelve a `undefined`, como no sea por el _matcher_ que usamos en el _assert_ del test...

Mirandolo desde el móvil, ¿le habías cambiado al mock del `jwt.verify` el mock que le pasabas que tenía que devolver porque había dos lugares donde se usaba la variable `mockToken` ? Línea 157.
Igualmente ahora está bien creo porque por ese motivo, veo mejor que el `getMockToken` este invocado en una variable ya que se va a usar más de una vez.

2023-04-24 10:16 UTC, DI3BOSS commented
> @DI3BOSS no hacemos un commit por un cambio de nombre de variable o por cambios en los imports. Cuando hagas los cambios, acuérdate de comprimir commits para que en cada commit haya cambios relevantes.

Vale, unificaré los commits para que sean menos y con contenido más relevante 💪.

2023-04-25 12:03 UTC, DI3BOSS commented
> @DI3BOSS no hacemos un commit por un cambio de nombre de variable o por cambios en los imports. Cuando hagas los cambios, acuérdate de comprimir commits para que en cada commit haya cambios relevantes.

He comprimido los commits y subido los cambios en la función `generateMockToken`  y en los tests que la usan.

2023-04-25 16:16 UTC, mariogl commented
Veo todo el rato este patrón:

´´´js
const { id: mockUserId } = mockTokenPayload;

const mockToken = generateMockToken(mockUserId);
´´´

Si lo que tengo siempre es un payload, ¿por qué la función generateMockToken no recibe un payload?

2023-04-25 17:04 UTC, DI3BOSS commented
> 

Tienes toda la razón. En realidad me iría mejor pasarle un `payload`, visto el patrón,  pero según entendía @MMLORENA queríamos pasarle un `id` a la función `mockUserPayload` pasarle la `id` de getMockToken en el test dónde se usa. Pero esto hace que sea necesario desestructurar `mockTokenPayload` para poder pasarle la `id` que contiene, a  esta misma función, en el resto de casos de uso que la necesitan para el _testing_.

2023-04-26 11:51 UTC, DI3BOSS commented
> Veo todo el rato este patrón:
> 
> ```js
> const { id: mockUserId } = mockTokenPayload;
> 
> const mockToken = generateMockToken(mockUserId);
> ```
> 
> Si lo que tengo siempre es un payload, ¿por qué la función generateMockToken no recibe un payload?

Refactorizada la función y los test. Ahora la función `generateMockToken` recibe un `token payload` como parámetro y los tests le pasan un `payload` como argumento cuando la invocan.

2023-04-26 11:54 UTC, DI3BOSS commented
> Y no he entendido en qué caso devuelve el mockToken undefined y qué has hecho para arreglarlo. ¿puedes indicar archivo?
@MMLORENA  cuando puedas, mira si te parecen bien los cambios para resolver la conversación. Al final le pasamos a la función generadora, siguiendo las observaciones de @mariogl, un ´token payload` en lugar de un `id`.

2023-04-26 14:49 UTC, MMLORENA requested changes

2023-04-27 11:29 UTC, DI3BOSS commented on src/server/controllers/userControllers/userControllers.test.ts
> +      const mockToken = generateMockToken(mockTokenPayload);
Corregido para que ahora, en este test, se le pase como `payload` el id de `existingUser`

2023-04-27 11:32 UTC, DI3BOSS commented on src/server/routers/usersRouter/usersRouter.test.ts
> +      const mockLuisToken = generateMockToken(mockUserPayload);
He extraído el `id` de `mockUserPayload` para que sea propiedad de `mockTokenPayload`  y pasarle este _mock_ a `generateMockToken` como argumento.

2023-04-29 16:02 UTC, MMLORENA submitted a review, later dismissed

2023-04-29 16:06 UTC, MMLORENA approved these changes

2023-04-29 16:06 UTC, mariogl commented
@DI3BOSS he retomado esta PR para mergearla ya para el cierre de sprint.

2023-04-29 16:06 UTC, merged