Add response 409 to register endpoint in swagger docs
coders-app/coders-app-identity-server pull request #31
Opened 2022-12-28 20:55 UTC by MMLORENA

2022-12-28 21:10 UTC, mariogl requested changes

2022-12-28 21:10 UTC, mariogl commented on src/openapi/openapi.json
> +            "description": "Error creating a new user"
¿Este mensaje no debería ser que el usuario ya existe?

2022-12-28 21:19 UTC, MMLORENA commented on src/openapi/openapi.json
> +            "description": "Error creating a new user"
Ok, entonces lo cambio del controller. Otra duda, ¿El front realmente va a usar la info del user?

2022-12-28 21:22 UTC, mariogl commented on src/openapi/openapi.json
> +            "description": "Error creating a new user"
Ojo, la descripción del error en la documentación del endpoint no tiene por qué ser igual que el mensaje que lleva la response (en este caso pueden coincidir, pero no tiene por qué, son dos cosas distintas).

Respecto a la pregunta, este servidor de identidad es genérico, no va a saber quién le envía registro ni qué necesitará, por lo tanto está bien devolver esos datos.

2022-12-28 22:22 UTC, MMLORENA commented on src/openapi/openapi.json
> +            "description": "Error creating a new user"
Okey. 
De todos modos lo he cambiado en el controller y especificado más los errores.

2022-12-29 07:52 UTC, benjaminrae submitted a review, later dismissed

2022-12-29 09:11 UTC, mariogl requested changes

2022-12-29 09:11 UTC, mariogl commented on src/openapi/openapi.json
> +            "description": "Error creating a new user"
Sigue faltando esto, ¿no?

2022-12-29 09:11 UTC, mariogl commented on src/server/routes/usersRouter/usersRouter.test.ts
>      test("Then it should respond with code 409 and 'Error creating a new user'", async () => {
Recordad mantener las descripciones de los tests sincronizadas con los cambios que hagamos en ellos. El error que se espera no es el que pone en la descripción.

2022-12-29 09:16 UTC, mariogl requested changes

2022-12-29 09:16 UTC, mariogl commented on src/server/controllers/userControllers/userControllers.test.ts
> +        "Error creating a new user"
Éste no es el mensaje que tiene que contener el error.

La descripción del test habría que adaptarla a esta ampliación de código.

2022-12-29 10:49 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.test.ts
> +        "Error creating a new user"
¿Qué quieres decir con: _Éste no es el mensaje que tiene que contener el error_?

2022-12-29 10:51 UTC, mariogl commented on src/server/controllers/userControllers/userControllers.test.ts
> +        "Error creating a new user"
Que el error emitido no tiene que tener un mensaje "Error creating a new user", habíamos dicho que poníamos otro, ¿no?

2022-12-29 11:04 UTC, MMLORENA commented on src/openapi/openapi.json
> +            "description": "Error creating a new user"
ahora si, cambiado

2022-12-29 11:04 UTC, MMLORENA commented on src/server/routes/usersRouter/usersRouter.test.ts
>      test("Then it should respond with code 409 and 'Error creating a new user'", async () => {
cierto

2022-12-29 11:11 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.test.ts
> +        "Error creating a new user"
Ahora tiene dos errores, por un lado, si se produce por un error de mongoose de duplicate key sera User already exists, en cambio si es por ejemplo, error de bcrypt o mongoose rejectea por algún motivo, tendrá un 500 y el mensaje será Error creating a new user. 
Lo he hecho así para customizar un poco más los errores qué se pueden producir ya que entiendo que pueden venir por varios motivos. 

¿Qué opinas?

2022-12-29 11:23 UTC, benjaminrae approved these changes

2022-12-29 11:28 UTC, mariogl commented on src/server/controllers/userControllers/userControllers.test.ts
> +        "Error creating a new user"
Perfe.

2022-12-29 11:28 UTC, mariogl approved these changes

2022-12-29 11:44 UTC, merged