Bugfix/token expires in
coders-app/coders-app-identity-server pull request #44
Opened 2023-01-02 17:40 UTC by MMLORENA

2023-01-02 18:27 UTC, mariogl requested changes

2023-01-02 18:27 UTC, mariogl commented on src/server/controllers/userControllers/userControllers.ts
> +const tokenExpiry = "2d";
Pongamos este plazo mejor en una variable de entorno.

2023-01-02 18:40 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.ts
> +const tokenExpiry = "2d";
Pensaba que era igual que el salt, pero pensandolo bien sí es algo que queremos que se modifique. Cambiado

2023-01-02 18:43 UTC, mariogl commented on src/server/controllers/userControllers/userControllers.ts
> +const tokenExpiry = "2d";
Perfe, agrúpalo con jwtSecret en el objeto de environment variables mejor, así está más organizado (haz un ammend y un push -f, no crees un nuevo commit).

2023-01-02 19:23 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.ts
> +const tokenExpiry = "2d";
Lo he visto tarde... y he hecho otras cosas más. No puedo hacer un amend ni un rebase. Lo tendré en cuenta para el resto

2023-01-03 13:17 UTC, mariogl commented on src/server/controllers/userControllers/userControllers.ts
> +const tokenExpiry = "2d";
Oki.

2023-01-03 13:17 UTC, mariogl submitted a review, later dismissed

2023-01-03 13:18 UTC, mariogl commented
Recuerda documentar la nueva variable del .env en el documento compartido que tenemos.

2023-01-03 13:45 UTC, MMLORENA commented
> Recuerda documentar la nueva variable del .env en el documento compartido que tenemos.

Ya está actualizado

2023-01-03 14:16 UTC, bertoforteza approved these changes

2023-01-03 14:31 UTC, merged