Feature/generate cookie with token
coders-app/coders-app-identity-server pull request #48
Opened 2023-01-04 11:59 UTC by benjaminrae

2023-01-05 08:51 UTC, bertoforteza submitted a review, later dismissed

2023-01-05 16:36 UTC, mariogl requested changes

2023-01-05 16:36 UTC, mariogl commented on src/server/controllers/userControllers/userControllers.ts
> +      .cookie("coders_identity_token", token, {
El nombre de la cookie y su validez es mejor que no estén en valores mágicos, pongámoslos en constantes en algún archivo de configuración.

2023-01-05 18:58 UTC, benjaminrae commented on src/server/controllers/userControllers/userControllers.ts
> +      .cookie("coders_identity_token", token, {
Perfecto, luego añado los cambios

2023-01-10 09:38 UTC, bertoforteza approved these changes

2023-01-10 11:53 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.test.ts
> +        message: "coders_identity_token has been set",
Creo que quedaría mejor no poner el mensaje en magic string

2023-01-10 11:53 UTC, MMLORENA commented on src/testUtils/cookieParser.ts
> +// 'coders_identity_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVuamFtaW4gQnJla2tlIiwiaXNBZG1pbiI6ZmFsc2UsImlkIjoiNjNiNTYxNTNlZGMxNDE5NDgxYjQ5MmUyIiwiaWF0IjoxNjcyODMxMzE2LCJleHAiOjE2NzMw
ups 🤐

2023-01-12 12:25 UTC, benjaminrae commented on src/server/controllers/userControllers/userControllers.test.ts
> +        message: "coders_identity_token has been set",
Si, de hecho ya esta hecho el objeto

2023-01-12 12:31 UTC, MMLORENA approved these changes

2023-01-12 12:33 UTC, merged