Feature/error messages
coders-app/coders-app-identity-server pull request #50
Opened 2023-01-09 16:55 UTC by Liluminalia

no esta terminado, el archivo de public messages esta practicamente "vacio" (hay que cambiar casi todos los mensajes), y en general no estan cambiados todos los errores a variables me faltan cositas, pero asi va de momento hoy

2023-01-09 16:59 UTC, benjaminrae commented
> no esta terminado, el archivo de public messages esta practicamente "vacio" (hay que cambiar casi todos los mensajes), y en general no estan cambiados todos los errores a variables me faltan cositas, pero asi va de momento hoy

Si el Pull Request no esta listo, podrias cambiarlo a draft? Asi evitamos un merge a master de una feature que no esta lista.

Otra cosa, intenta seguir las convenciones que se han establecido para naming de commits. Hemos estado usando el imperativo con la primera letra en mayuscula.

2023-01-09 17:07 UTC, benjaminrae requested changes

2023-01-10 12:05 UTC, MMLORENA commented
@Liluminalia Creo que la refactorización sería más limpia si crearamos directamente un único Custom Error para cada tipo de error y lo almacenaramos dentro de un objeto y así exportarlo, en lugar de crear un archivo con variables de mensajes de error. 

Un ejemplo sería:
 ```js

 export const loginErrors = {
  userNotFoundError: new CustomError(
    "Username not found",
    unauthorizedCode,
    incorrectCredentialsMessage
  ),

  incorrectPasswordError: new CustomError(
    "Incorrect password",
    unauthorizedCode,
    incorrectCredentialsMessage
  ),
};

export const registerErrors = {
  alreadyRegisteredError: new CustomError(
    "User already exists",
    conflictsErrorCode,
    "That username is taken"
  ),
};
```

2023-01-10 12:07 UTC, MMLORENA requested changes

2023-01-17 08:57 UTC, closed without merging