Feature/refactor types files
coders-app/coders-app-identity-server pull request #65
Opened 2023-01-26 12:52 UTC by bertoforteza

2023-01-26 13:11 UTC, mariogl commented
¿Puedes añadirle una descripción a la PR para dar contexto?

2023-01-26 13:15 UTC, mariogl requested changes
¿Podemos poner los tipos de cada módulo en un archivo `types.ts` en la misma carpeta del módulo? Lo de hacer una carpeta `types` es por si va a haber más archivos además del `types`.

2023-01-26 15:55 UTC, bertoforteza commented
> 

Pensaba que era más correcto tenerlo dentro de una carpeta pero lo voy a cambiar.

2023-01-26 15:57 UTC, bertoforteza commented
> ¿Puedes añadirle una descripción a la PR para dar contexto?

Descripción añadida.

2023-01-26 21:13 UTC, mariogl commented
No habría que rehacer todos los commits para eso, pero sí creo que esta feature podría quedar en muchos menos commits. Si no me equivoco, hay un commit por cada movimiento de archivo, ¿no?

2023-01-29 19:47 UTC, MMLORENA commented
@bertoforteza no entiendo porqué se han movido tantos types de sitio. ¿Yo diria que hay tipos que se usan en más de un lugar y por tanto se deberían haber quedado en el archivo types dónde estaban o realmente todos los movidos solo se usan una vez?

2023-01-29 21:48 UTC, bertoforteza commented
> No habría que rehacer todos los commits para eso, pero sí creo que esta feature podría quedar en muchos menos commits. Si no me equivoco, hay un commit por cada movimiento de archivo, ¿no?

Cuando leí la descripció de la tarjeta entendí que había que hacer un commit por cada archivo que se movía pero igual sería mejor un comit por cada módulo.

2023-01-29 21:52 UTC, bertoforteza commented
> @bertoforteza no entiendo porqué se han movido tantos types de sitio. ¿Yo diria que hay tipos que se usan en más de un lugar y por tanto se deberían haber quedado en el archivo types dónde estaban o realmente todos los movidos solo se usan una vez?

Lo estuve revisando y cada uno de los que se han movido sólo se utilizan en un módulo (email o server) y algunos también en el módulo de factories, pero factories siempre va a utilizar interfaces de los demás módulos.
El que queda en el archivo ```types``` global es el tipo ```WithRequiredProperties```, que nos pareció muy genérica y que se podía utilizar en más módulos más adelante.

2023-02-04 19:03 UTC, mariogl commented
@bertoforteza Bert, lo veo bien. Sólo una última cosa: yo proponía un archivo `types.ts` en la carpeta de cada módulo. Veo que has usado una carpeta types, no lo veo mal pero entonces el archivo se tiene que llamar `index.ts`.

Resumen: quedaría sólo coger cada archivo `/types/types.ts` y renombrarlo a `/types/index.ts`.

2023-02-07 11:35 UTC, natigherardi submitted a review, later dismissed

2023-02-08 16:01 UTC, catatarelli approved these changes

2023-02-08 16:02 UTC, bertoforteza commented
> @bertoforteza Bert, lo veo bien. Sólo una última cosa: yo proponía un archivo `types.ts` en la carpeta de cada módulo. Veo que has usado una carpeta types, no lo veo mal pero entonces el archivo se tiene que llamar `index.ts`.
> 
> Resumen: quedaría sólo coger cada archivo `/types/types.ts` y renombrarlo a `/types/index.ts`.

@mariogl Ya está renombrado como `/types/index.ts`.

2023-02-08 16:10 UTC, mariogl approved these changes

2023-02-08 16:15 UTC, merged