Create User schema & model
coders-app/coders-app-identity-server pull request #9
Opened 2022-12-23 17:14 UTC by MMLORENA

2022-12-23 17:18 UTC, mariogl requested changes

2022-12-23 17:18 UTC, mariogl commented on src/database/models/User.ts
> +  email: {
Iría guay que el email fuera unique, ¿no?

2022-12-23 17:18 UTC, mariogl commented on src/database/models/User.ts
> +  createdAt: {
Mira el link que os puse para los timestamps de MongoDB.

2022-12-23 19:52 UTC, MMLORENA commented on src/database/models/User.ts
> +  createdAt: {
No he encontrado el link pero leyendo la documentación de Mongoose lo he configurado así ya que entiendo que por ahora no vamos a customizar createdAt ni updatedAt con otro naiming.

2022-12-24 10:57 UTC, mariogl commented on src/database/models/User.ts
> +  email: {
@MMLORENA avisad cuando hagáis cambios en respuesta a una petición, please.

2022-12-24 10:57 UTC, mariogl approved these changes

2022-12-24 12:16 UTC, benjaminrae approved these changes

2022-12-24 12:18 UTC, merged