Feature/cod 136 get user data
coders-app/coders-app-identity-server pull request #96
Opened 2023-03-28 10:32 UTC by MMLORENA

Añadido getUserData controller para ir a la base de datos con el id del usuario y devolver el name, email y si es Admin. No he devuelto todos los datos del usuario porque creo que son innecesarios, pero què opináis @coders-app/devs . 

He eliminado de la función de connectDataBase que se devuelva la password del usuario. 

Añadido el endpoint de getUserData a usersRouter y testeado.

2023-03-28 10:38 UTC, MMLORENA commented on src/server/routers/usersRouter/usersRouter.test.ts
> +      const mockenPayload: CustomTokenPayload = {
@coders-app/devs Deberíamos crear una función para generar el mockPayload y así controlar el token que creeamos. Por ahora, he creado un nuevo token en el test pero en el refactor del getUserDetails creo que deberíamos incluir crear está función para que pida por parametros los datos del usuario.

2023-03-28 10:38 UTC, MMLORENA commented on src/server/routers/usersRouter/usersRouter.test.ts
> +        .set("Cookie", [correctCookie])
El naming de correctCookie ahora quizás no queda del todo claro porque en el anterior test también hay una cookie valida. 
Ahora se crean dos cookies diferentes, uno con un usuario creado en la DB y otro que no.

2023-03-28 10:38 UTC, MMLORENA commented on src/server/routers/usersRouter/usersRouter.test.ts
> +        name: newUserData.name,
No he podido usar los datos de newUser directamente porque hay un problema de tipado entre las factory y los tipos de usuario. Creo que deberíamos darle una vuelta a los tipados de los usario y a las factories. Ahora tenemos una factory de un usuario completo que no debería devolver una password.

2023-03-29 11:17 UTC, Killuina commented on src/server/controllers/userControllers/userControllers.test.ts
> +  describe("When it receives a custom request with  with user details id: '1234' and the user exists", () => {
Se te ha colado un doble "with" por aquí 😁

2023-03-29 11:17 UTC, Killuina commented on src/server/controllers/userControllers/userControllers.test.ts
> +    test("Then it should invoke response's method status with 200 and json with with received user data", async () => {
Por aquí también

2023-03-29 11:18 UTC, Killuina commented on src/server/controllers/userControllers/userControllers.test.ts
> +  describe("When it receives a custom request with  with user details id: '1234' and the user doesn't exists", () => {
Y por aquí

2023-03-29 11:21 UTC, benjaminrae requested changes

2023-03-29 11:21 UTC, benjaminrae commented on src/server/controllers/userControllers/userControllers.ts
> +    const user = await User.findById(userId);
Podriamos añadir `.exec()` para quitar el code smell aqui

2023-03-29 11:21 UTC, benjaminrae commented on src/server/controllers/userControllers/userControllers.test.ts
> +  describe("When it receives a custom request with  with user details id: '1234' and the user exists", () => {
with doble espacio y otro with 😉

2023-03-29 11:21 UTC, benjaminrae commented on src/server/controllers/userControllers/userControllers.test.ts
> +    test("Then it should invoke response's method status with 200 and json with with received user data", async () => {
"and json with with"

2023-03-29 11:21 UTC, benjaminrae commented on src/server/controllers/userControllers/userControllers.test.ts
> +  describe("When it receives a custom request with  with user details id: '1234' and the user doesn't exists", () => {
Otro with with

2023-03-29 11:45 UTC, isdicoders requested changes

2023-03-29 11:45 UTC, isdicoders commented on src/database/connectDatabase.ts
> +      delete ret.password;
@coders-app/devs Para estas cosas creo que es mejor utilizar la proyección de las queries particulares que manejen un campo password. La proyección nos permite elegir qué campos del documento aparecen o no en el resultado.

https://mongoosejs.com/docs/api/model.html#Model.find()

2023-03-29 11:45 UTC, isdicoders commented on src/server/controllers/userControllers/userControllers.test.ts
> +  describe("When it receives a custom request with  with user details id: '1234' and the user exists", () => {
Es un with-with

2023-03-29 11:45 UTC, isdicoders commented on src/server/controllers/userControllers/userControllers.test.ts
> +      const expectedNotFoundUser = new CustomError(
En esta variable no se va a guardar un user, por tanto el naming debería apuntar a un error, no a un user.

2023-03-30 04:03 UTC, isdicoders commented on src/server/routers/usersRouter/usersRouter.test.ts
> +      const mockenPayload: CustomTokenPayload = {
Creada tarea en el backlog de producto.

2023-03-30 04:24 UTC, isdicoders requested changes

2023-03-30 04:24 UTC, isdicoders commented on src/server/routers/usersRouter/usersRouter.test.ts
> +      const mocken = jwt.sign(mockenPayload, jwtSecret);
En CodersOne mejor no usemos `mocken` para este identificador de variable (es una noticia triste, lo sé).

2023-03-30 04:24 UTC, isdicoders commented on src/server/routers/usersRouter/usersRouter.test.ts
> +        .set("Cookie", [correctCookie])
Yo pondría:
`randomUserCookie`: cookie válida pero de usuario random (la actual `correctCookie`)
`incorrectCookie`: cookie con token no válido
`userLuisCookie`: cookie con token de usuario existente

En resumen: cambiar `correctCookie` por `randomUserCookie`

2023-03-30 04:25 UTC, isdicoders commented on src/server/routers/usersRouter/usersRouter.test.ts
> +        name: newUserData.name,
Le pegamos un repaso hoy.

2023-03-30 07:50 UTC, MMLORENA commented on src/server/routers/usersRouter/usersRouter.test.ts
> +        .set("Cookie", [correctCookie])
Perfe

2023-03-30 07:53 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.test.ts
> +  describe("When it receives a custom request with  with user details id: '1234' and the user doesn't exists", () => {
corrected

2023-03-30 07:59 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.ts
> +    const user = await User.findById(userId);
Me parece bien

2023-03-30 08:33 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.ts
> +      const notFoundUser = new CustomError(
Me parece bien!

2023-03-30 08:45 UTC, MMLORENA commented on src/database/connectDatabase.ts
> +      delete ret.password;
Okey, tomo nota. No conocia las proyecciones de mongoose. En un principio había quitado la password del modelo porque devolvía los datos de todo el user, pero ahora solo respondo con el nombre, isAdmin y su email, por tanto, entiendo que no es necesario.

2023-03-30 08:46 UTC, MMLORENA commented on src/server/controllers/userControllers/userControllers.test.ts
> +      const expectedNotFoundUser = new CustomError(
Perfe

2023-04-01 05:09 UTC, isdicoders submitted a review, later dismissed

2023-04-01 13:01 UTC, MMLORENA commented
> Añadido getUserData controller para ir a la base de datos con el id del usuario y devolver el name, email y si es Admin. No he devuelto todos los datos del usuario porque creo que son innecesarios, pero què opináis @coders-app/devs .
> 
> He eliminado de la función de connectDataBase que se devuelva la password del usuario.
> 
> Añadido el endpoint de getUserData a usersRouter y testeado.

He añadido a la PR la extracción de constants el error de userDataError para seguir con el refactor de los errores y aplicarlo ya correctamente en esta nuevo endpoint

2023-04-01 13:11 UTC, merged